runtime: nodejs18

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 0
  max_instances: 10

handlers:
# Static assets from build
- url: /assets
  static_dir: dist/public/assets
  secure: always

# Uploads directory  
- url: /uploads
  static_dir: public/uploads
  secure: always

# Built static files (favicon, etc.) from dist/public
- url: /(.+\.(ico|png|jpg|jpeg|gif|css|js|map))$
  static_files: dist/public/\1
  upload: dist/public/(.+\.(ico|png|jpg|jpeg|gif|css|js|map))$
  secure: always

# Original public files (for uploaded images, etc.)
- url: /(.+\.(ico|png|jpg|jpeg|gif))$
  static_files: public/\1
  upload: public/(.+\.(ico|png|jpg|jpeg|gif))$
  secure: always
  
# All other routes go to the Node.js app
- url: /.*
  script: auto
  secure: always