name = "inkalchemy"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "node scripts/build-worker.js"

# Production environment configuration
[env.production]
vars = { NODE_ENV = "production" }

# Note: Secrets (DATABASE_URL, VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY)
# should be set using: wrangler secret put <SECRET_NAME>
# or via the Cloudflare Workers dashboard

[assets]
directory = "dist/public"
not_found_handling = "single-page-application"