name = "inkalchemy"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "node scripts/build-worker.js"

# Enable environment variables from Replit secrets
[env.production.vars]
NODE_ENV = "production"

# Environment variables will be automatically loaded from Replit secrets
# DATABASE_URL, VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY

[[routes]]
pattern = "*"
zone_name = ""

[assets]
directory = "dist/public"
not_found_handling = "single-page-application"